set-option -sa terminal-overrides ",xterm*:Tc"
set-option -g mouse on
set-option -g set-clipboard on

# set vi options
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-pipe-and-cancel "pbcopy"

bind C-l send-keys 'C-l' # use C-b C-l to clear screen as C-l is used by vim

bind C-n select-window -n
bind C-p select-window -p

# resize the active pane (prefix, then repeat H/J/K/L)
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on


# style the bar
set-option -g status-position bottom
# set-option -g status-right "%a %d %b %I:%M %p"
set -g status-style bg=black
setw -g window-status-current-style "fg=#171b1f bg=#d08770 bold"
setw -g window-status-style "fg=#888888"
setw -g window-status-current-format " #I:#W "
setw -g window-status-format " #I:#W "
# set -g status-justify centre
# set -g status-left-length 80
# set -g status-left '#[bold]>>> #S'
# set -g pane-border-style fg=#171b1f
# set -g pane-active-border-style "bg=#171b1f fg=#171b1f"
set -g pane-border-style fg=#555555
set -g pane-active-border-style "bg=default fg=#d08770"
set -g pane-border-lines heavy

# sesh recommended
set -g detach-on-destroy off

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run-shell '~/.tmux/plugins/tpm/tpm'


